Create Jumping.c
ankitapuri/DSA-guide pull request #147
Opened 2020-10-14 22:28 UTC by PrakashAditya17

## JumpSearch Algorithm 
With complexity O(n^0.5)

##  Assigned Issue Number
#93 

## Language used 
C

2020-10-14 22:29 UTC, PrakashAditya17 commented
Hello @ankitapuri , thanks for assigning me, I have added the code in required folder.

2020-10-16 04:45 UTC, ankitapuri requested changes
Explain your code more by using comments

2020-10-16 09:17 UTC, PrakashAditya17 commented
Added some comments in the updated file.

2020-10-16 17:41 UTC, ankitapuri approved these changes

2020-10-16 17:41 UTC, merged