Create Bead Sort.py
ankitapuri/DSA-guide pull request #210
Opened 2021-02-17 05:53 UTC by kmryashasvi

## Related Issue
 Adding python code for bead sort

Closes: #202
#### Describe the changes you've made
added new file with comment and using function for sorting

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run it in my local ide

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

2021-02-17 13:26 UTC, ankitapuri requested changes
It has error in line 9

2021-02-17 13:28 UTC, kmryashasvi commented
hahaha,
very sorry,
 it is a comment without slashes

2021-02-17 13:30 UTC, kmryashasvi commented
Please check once again

2021-02-19 05:07 UTC, ankitapuri approved these changes

2021-02-19 05:09 UTC, merged