Create  Local Minima in a Given Array.c
ankitapuri/DSA-guide pull request #257
Opened 2021-03-05 17:04 UTC by kmryashasvi

Closes: #214

#### Describe the changes you've made
added a file in C

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

2021-03-07 04:52 UTC, ankitapuri requested changes
Add few more comments to explain the code even to a beginner .

2021-03-07 16:59 UTC, ankitapuri approved these changes

2021-03-07 17:00 UTC, ankitapuri reviewed
add in arrays folder creating C folder in it

2021-03-08 02:43 UTC, kmryashasvi commented
![image](https://user-images.githubusercontent.com/66861659/110267612-326ad580-7fe6-11eb-89b9-ce8994236355.png)
Done

2021-03-08 05:14 UTC, ankitapuri approved these changes

2021-03-08 05:18 UTC, merged