[feature-1] Added Staircase Search in CPP
ankitapuri/DSA-guide pull request #263
Opened 2021-03-08 05:51 UTC by kiruba-r11

## Related Issues
  - Added an important problem named `StairCase Search`.

Closes: #262 

#### Describe the changes you've made
I have completely implemented a CPP program that takes the input of the row and column sorted matrix and a key and performs the types of search to find the key in the matrix. All the three searching types, exploit the property of row and column sorted elements of the matrix and optimizes the problem.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This has been tested by generating a set of random inputs using a generator and verified the outputs manually.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-03-08 05:52 UTC, kiruba-r11 commented
@ankitapuri Please have a look at it

2021-03-10 03:22 UTC, ankitapuri requested changes
Its printing the found statement thrice

2021-03-10 03:28 UTC, kiruba-r11 commented
@ankitapuri It's because the problem is solved in three different complexities and is printing the results. It is just to verify that all three approaches provide same output.

2021-03-10 03:56 UTC, ankitapuri commented
Just separate the results in output as well by providing the complexities

2021-03-10 04:09 UTC, kiruba-r11 commented
@ankitapuri Please have a look at it.

2021-03-10 15:59 UTC, merged